### ISSUE TITLE
error running quickstart/ example

### ISSUE THREAD

**Issue by jrive87** [Qorvo/PyQSPICE#1]
I don't know how else to request help, so I apologize for using this "issues" tab to do so.

I tried following the Quick Start/ example for PyQSPICE, Python Module for Qorvo's QSPICE™

and ran into the following error on the line:

`run = pqs("UJ3N065080")`
 
as shown below:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-16f49b4ed263>", line 1, in <module>
    pqs('UJ3N065080')
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyQSPICE\qspice.py", line 43, in __init__
    self.path['base'] = fname.removesuffix('.qsch').removesuffix('.qraw').removesuffix('.cir')
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by MasashiNogawa** [comment]
Would you mind to share your command line operations, after your downloading this repository?  I suspect your working directory is upper level and you don't see this UJ3N065080'.qsch example schematic.

**Comment by MasashiNogawa** [comment]
...no activities, assume it's solved.  Please kindly issue new one if it's not closed yet.
