### ISSUE TITLE
Uninitialized variable in qspice.py

### ISSUE THREAD

**Issue by XICEngineer** [Qorvo/PyQSPICE#2]
In clsQSPICE.InitPlot, variable fe is only initialized if one of the fonts is found. This causes qspice.py to crash if neither font is found. One fix is to initialize fe to None prior to the first fe assignment, so that fe is guaranteed to exist.  

        fe = None
        mfont = self.gpath['home'] + "/.config/matplotlib/ResourceHanRoundedJP-Medium.ttf"
        if os.path.exists(mfont): fe = fm.FontEntry(fname=mfont, name="Resource Han Rounded JP Medium")
        mfont = self.gpath['home'] + "/.config/matplotlib/GenJyuuGothicL-Medium.ttf"
        if os.path.exists(mfont): fe = fm.FontEntry(fname=mfont, name="GenJyuuGothicL Medium")
        if fe:
            fm.fontManager.ttflist.insert(0,fe)
            mpl.rcParams['font.family'] = fe.name

**Comment by MasashiNogawa** [comment]
@XICEngineer 

Thanks for your report and fix.  I'll take your fix in as soon as I can locate my time on this.

**Comment by masa300V** [comment]
Ver.2024.02.19 released.

**Comment by MasashiNogawa** [comment]
Ver.2024.02.19 releaed.

https://pypi.org/project/PyQSPICE/2024.2.19/
